insert into event VALUES (1, 2, 0, 1, 10);
insert into thing VALUES (1, " Letra",                      "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/letra.png",    " alimentar",  " Esta loja tem um texto longo1",  " http://google.com", 656, 656);
insert into thing VALUES (2, " Frubis",                     "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/frubis.png",    " alimentar",  " Esta loja tem um texto longo2",  " http://google.com", 400, 574);
insert into thing VALUES (3, " Tété",                       "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/tete.png",      " alimentar",  " Esta loja tem um texto longo3",  " http://google.com", 435, 258);
insert into thing VALUES (4, " Casa Grande",                "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/casagrande.png"," alimentar",  " Esta loja tem um texto longo",   " http://google.com", 300, 213);
insert into thing VALUES (5, " Antiga Barbearia de Bairro", "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/barb.png",      " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 220, 128);
insert into thing VALUES (6, " Boa Boca",                   "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/boca.png",      " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 317, 427);
insert into thing VALUES (7, " Bolas de Praia",             "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/bola.png",      " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 300, 200);
insert into thing VALUES (8, " FrutaFormas",                "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/formas.png",    " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 200, 200);
insert into thing VALUES (9, " José Gourmet",               "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/jose.png",      " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 446, 343);
insert into thing VALUES (10," Meia-Dúzia",                 "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/extra_jam.png", " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 568, 370);
insert into thing VALUES (11," Pingunça",                   "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/pinguca.png",  " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 283, 267);
insert into thing VALUES (12," Yonest",                     "http://citysdk.tagus.ist.utl.pt/~jtrindade/showcase/yonest_logo.png", " alimentar",  " Esta loja tem um texto longo",   " http://google.com", 400, 400);
