insert into event VALUES (1, 2, 0, 1, 10);
insert into thing VALUES (1,   " Letra",                       " http://www.meiosepublicidade.pt/wp-content/uploads/2014/01/letra.jpg",                                                                                                 " alimentar",  " Esta loja tem um texto longo1",  " http://google.com");
insert into thing VALUES (2,   " Frubis",                      " http://www.frubisworld.com/Frubis/img/Pacotes_FRUBIS_edit_04.png?14",                                                                                                  " alimentar",  " Esta loja tem um texto longo2",  " http://google.com");
insert into thing VALUES (3,   " Tété",                        " http://tete.pt/imagens/produtos/m3.jpg",                                                                                                                               " alimentar",  " Esta loja tem um texto longo3",  " http://google.com");
insert into thing VALUES (4,   " Casa Grande",                 " http://www.meiosepublicidade.pt/wp-content/uploads/2014/01/ALTA-300x213.jpg",                                                                                          " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (5,   " Antiga Barbearia de Bairro",  " http://www.100ml.pt/abb/imagens/logo_abb.png",                                                                                                                         " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (6,   " Boa Boca",                    " http://boaboca-gourmet.com/wp/wp-content/uploads/2011/11/bboca_bisccanela1.jpg",                                                                                       " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (7,   " Bolas de Praia",              " http://www.meiosepublicidade.pt/wp-content/uploads/2014/01/bolas-de-praia-300x200.jpg",                                                                                " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (8,   " FrutaFormas",                 " http://cdn.nexttv.sapo.pt/user/channels/9e/18f/40878/logo18e3b187ab83f30c9e8d9b2f018e2ae2-200x200.png",                                                                " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (9,   " José Gourmet",                " http://erinspens.files.wordpress.com/2011/12/jose-packaging.jpg",                                                                                                      " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (10,  " Meia-Dúzia",                  " http://www.winespiritus.com/906-1352-thickbox/extra-jam-meia-duzia-pack-6x75gr-extra-jam.jpg",                                                                         " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (11,  " Pingunça",                    " http://static.squarespace.com/static/5151aed5e4b0030300310dbf/515b73b7e4b03ae0a10d07be/515b73cee4b0daad6e73a758/1364997939577/pingu%C3%A7a-flavours.jpg?format=200w",  " alimentar",  " Esta loja tem um texto longo",   " http://google.com");
insert into thing VALUES (12,  " Yonest",                      " http://www.yonest.pt/img/yonest_logo.png",                                                                                                                             " alimentar",  " Esta loja tem um texto longo",   " http://google.com");

